import React from 'react';
import {ResponsiveContainer, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis, Radar, Tooltip, PieChart, Pie, Cell, AreaChart, Area, XAxis, CartesianGrid} from 'recharts';
import {ArrowUpRight,Activity,Signal,Users,Wallet,Headphones,ArrowRight,Mail,Bell,ShieldCheck,Radio,Check} from 'lucide-react';
const colors=['#a9c995','#efa477','#93b6c0','#a79ec4','#d88982'];
export function DotMeter({value=0,count=32,color='green',label='Proportion filled'}){return <div className={`dot-meter ${color}`} role="meter" aria-valuenow={Math.round(value)} aria-valuemin={0} aria-valuemax={100} aria-label={label}>{Array.from({length:count},(_,i)=><i className={i<Math.round(value/100*count)?'lit':''} key={i}/>)}</div>}
function sums(rows,key,field){const map={};rows.forEach(r=>map[r[key]]=(map[r[key]]||0)+(field?Number(r[field]):1));return Object.entries(map).map(([name,value],i)=>({name,value,color:colors[i%colors.length]}));}
function BarRows({data,onSelect,suffix='',max,format}){const limit=max||Math.max(...data.map(d=>d.value),1);return <div className="visual-bar-rows">{data.map((d,i)=><button key={d.name} onClick={()=>onSelect?.(d.name)} disabled={!onSelect} className="visual-bar-row" aria-label={`${d.name}: ${format?format(d.value):d.value}${suffix}`}><div><span><i style={{background:d.color||colors[i%colors.length]}}/>{d.name}</span><strong>{format?format(d.value):d.value}{suffix}</strong></div><div className="bar-track"><span style={{width:`${d.value/limit*100}%`,background:d.color||colors[i%colors.length]}}/></div></button>)}</div>}
function Donut({data,label='records',format=v=>v.toLocaleString()}){const total=data.reduce((a,d)=>a+d.value,0);return <div className="donut-layout"><div className="donut-plot" role="img" aria-label={data.map(d=>`${d.name}: ${format(d.value)}`).join(', ')}><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={total?data:[{name:'No records',value:1}]} dataKey="value" innerRadius="72%" outerRadius="93%" paddingAngle={total?5:0} cornerRadius={4} stroke="none" startAngle={90} endAngle={-270} isAnimationActive={false}>{(total?data:[{}]).map((d,i)=><Cell fill={total?d.color||colors[i%colors.length]:'#394145'} key={i}/>)}</Pie><Tooltip formatter={v=>format(v)} contentStyle={{background:'#242e32',border:'1px solid #536168',borderRadius:8}}/></PieChart></ResponsiveContainer><div className="donut-center"><strong>{format(total)}</strong><small>{label}</small></div></div><div className="donut-key">{data.map((d,i)=><div key={d.name}><i style={{background:d.color||colors[i%colors.length]}}/><span>{d.name}</span><b>{total?Math.round(d.value/total*100):0}%</b><small>{format(d.value)}</small></div>)}{!data.length&&<span>No records yet</span>}</div></div>}
function VisualCard({kicker,title,caption,children}){return <section className="card insight-card"><div className="insight-heading"><div><span className="eyebrow">{kicker}</span><h2>{title}</h2></div><Activity size={15}/></div>{children}<div className="insight-caption">{caption}</div></section>}
export function QualityRadar({compact=false}){const data=[{axis:'Uptime',value:99.98},{axis:'Latency',value:79},{axis:'Capacity',value:86},{axis:'Stability',value:94},{axis:'Redundancy',value:92}];return <section className={`card quality-card ${compact?'compact':''}`}><div className="card-heading"><div><span className="eyebrow">SERVICE QUALITY / DEMO</span><h2>Know where the network stands</h2><p>Normalized scores · Higher is better</p></div><Signal size={17}/></div><div className="radar-body"><div className="radar-chart" role="img" aria-label="Quality scores: uptime 99.98, latency 79, capacity 86, stability 94, redundancy 92 out of 100"><ResponsiveContainer width="100%" height="100%"><RadarChart data={data} outerRadius="69%"><PolarGrid stroke="#405056"/><PolarAngleAxis dataKey="axis" tick={{fill:'#a6b5bc',fontSize:9}}/><PolarRadiusAxis domain={[0,100]} tick={false} axisLine={false}/><Radar name="Quality score" dataKey="value" stroke="#9ebfc3" fill="#80aeb6" fillOpacity={.19} strokeWidth={1.6} dot={{r:3,fill:'#b0d2d1'}} isAnimationActive={false}/><Tooltip contentStyle={{background:'#253136',border:'1px solid #52666c',borderRadius:8}}/></RadarChart></ResponsiveContainer></div><div className="radar-summary"><span className="warn">LATENCY WATCH</span><h3>One weak link.<br/>A clear next step.</h3><p>Dhanmondi's 12.4 ms latency is above the 10 ms target.</p><div><i className="dot orange-dot"/>Inspect the orange POP in the 3D view.</div></div></div></section>}
export function DashboardSignals({role,customers,tickets,bills,onNavigate}){const active=customers.filter(c=>c.status==='Active').length,paid=bills.filter(b=>b.status==='Paid').reduce((a,b)=>a+b.amount,0),total=bills.reduce((a,b)=>a+b.amount,0),open=tickets.filter(t=>t.status!=='Resolved').length;return <div className="visual-stat-grid"><button className="card visual-stat" onClick={()=>onNavigate('Customers')}><div className="visual-stat-title"><span>Subscriber health</span><Users size={16}/></div><div className="visual-stat-number">{Math.round(active/Math.max(customers.length,1)*100)}<small>% active</small><span>{active} / {customers.length}</span></div><div className="subscriber-matrix">{customers.map(c=><i key={c.id} title={`${c.name}: ${c.status}`} className={c.status.toLowerCase()}/>)}</div><footer><span>One dot = one seeded customer</span><ArrowUpRight size={13}/></footer></button><button className="card visual-stat" onClick={()=>onNavigate('Billing & payments')}><div className="visual-stat-title"><span>Collection progress</span><Wallet size={16}/></div><div className="visual-stat-number">{total?Math.round(paid/total*100):0}<small>% collected</small></div><DotMeter value={total?paid/total*100:0} color="orange" count={28}/><footer><span>৳{paid.toLocaleString()} of ৳{total.toLocaleString()}</span><ArrowUpRight size={13}/></footer></button><button className="card visual-stat" onClick={()=>onNavigate('Network')}><div className="visual-stat-title"><span>Core capacity</span><Signal size={16}/></div><div className="visual-stat-number">46.82<small>/ 100 Gbps</small></div><div className="capacity-visual"><span style={{width:'46.82%'}}/><i style={{left:'80%'}}/></div><footer><span>53.18 Gbps headroom · Demo</span><ArrowUpRight size={13}/></footer></button><button className="card visual-stat" onClick={()=>onNavigate('Support tickets')}><div className="visual-stat-title"><span>Support workload</span><Headphones size={16}/></div><div className="visual-stat-number">{open}<small>need attention</small></div><div className="ticket-dot-row">{['Critical','High','Normal'].map((p,i)=><div key={p}><span>{p}</span><div>{tickets.filter(t=>t.priority===p&&t.status!=='Resolved').map(t=><i key={t.id} style={{background:[colors[4],colors[1],colors[2]][i]}} title={t.title}/>)}{!tickets.some(t=>t.priority===p&&t.status!=='Resolved')&&<small>0</small>}</div></div>)}</div><footer><span>Priority distribution</span><ArrowUpRight size={13}/></footer></button></div>}
export function PageInsights({page,customers,tickets,bills,jobs,items,leads,settings,read,onFilter}){
 let left,right;
 const money=v=>'৳'+v.toLocaleString();
 if(page==='Customers'){
  left=<VisualCard kicker="CUSTOMER MIX" title="Connection status at a glance" caption="All customer records, before table filters."><Donut data={['Active','Pending','Suspended'].map((name,i)=>({name,value:customers.filter(c=>c.status===name).length,color:[colors[0],colors[2],colors[4]][i]}))} label="customers"/></VisualCard>;
  right=<VisualCard kicker="GEOGRAPHIC DISTRIBUTION" title="Where your customers connect" caption="Select an area to filter the customer directory."><BarRows data={sums(customers,'area')} onSelect={onFilter}/></VisualCard>;
 }else if(page==='Sales pipeline'){
  left=<VisualCard kicker="PIPELINE FLOW" title="From interest to installation" caption="Stage widths represent current lead counts, not conversion rates."><div className="funnel-visual">{['New lead','Qualified','Proposal'].map((stage,i)=>{const count=leads.filter(l=>l.stage===stage).length;return <div key={stage}><span>0{i+1}</span><div style={{width:Math.max(25,count/Math.max(leads.length,1)*100)+'%',background:colors[i]}}><b>{count}</b></div><small>{stage}</small></div>})}</div></VisualCard>;
  right=<VisualCard kicker="OPPORTUNITY VALUE" title="Monthly revenue in the pipeline" caption="Sum of prospective monthly plan prices. No probability weighting."><BarRows data={sums(leads,'stage','value')} format={money}/></VisualCard>;
 }else if(page==='Services & plans'){
  left=<VisualCard kicker="PACKAGE ADOPTION" title="The plans your customers choose" caption="Current subscriptions across the seeded customer base."><Donut data={sums(customers,'plan')} label="subscriptions"/></VisualCard>;
  right=<VisualCard kicker="SPEED TIERS" title="The right bandwidth for every need" caption="Advertised package speeds · Symmetric upload and download."><BarRows data={[{name:'Essential 50',value:50},{name:'Velocity 100',value:100},{name:'Business 500',value:500}]} suffix=" Mbps" max={500}/></VisualCard>;
 }else if(page==='Support tickets'){
  left=<VisualCard kicker="QUEUE BALANCE" title="A visual pulse of your support queue" caption="Updates as tickets move through the support workflow."><Donut data={sums(tickets,'status')} label="tickets"/></VisualCard>;
  right=<VisualCard kicker="PRIORITY MAP" title="Urgency before volume" caption="Each tile represents one ticket. Resolved tickets are excluded."><div className="priority-matrix">{['Critical','High','Normal'].map((p,i)=><div key={p}><span>{p}</span><div>{tickets.filter(t=>t.priority===p&&t.status!=='Resolved').map(t=><i title={`${t.id}: ${t.title}`} key={t.id} style={{background:[colors[4],colors[1],colors[2]][i]}}/>)}<b>{tickets.filter(t=>t.priority===p&&t.status!=='Resolved').length}</b></div></div>)}</div></VisualCard>;
 }else if(page==='Field service'){
  left=<VisualCard kicker="JOB PROGRESS" title="The path to a connected customer" caption="Live counts from the installation board below."><div className="journey-visual">{['Scheduled','In progress','Completed'].map((s,i)=><React.Fragment key={s}>{i>0&&<ArrowRight size={18}/>}<div><span className={i===2?'complete':''}>{i===2?<Check size={22}/>:i+1}</span><b>{jobs.filter(j=>j.status===s).length}</b><small>{s}</small></div></React.Fragment>)}</div></VisualCard>;
  right=<VisualCard kicker="TECHNICIAN LOAD" title="Balance the work ahead" caption="Scheduled and in-progress visits per technician."><BarRows data={sums(jobs.filter(j=>j.status!=='Completed'),'agent')}/></VisualCard>;
 }else if(page==='Inventory'){
  left=<VisualCard kicker="EQUIPMENT LIFECYCLE" title="Know what is ready to deploy" caption="One tile = one asset. Counts update with customer assignments."><div className="equipment-tiles">{items.map((item,i)=><div key={item.id} title={`${item.name} · ${item.status}`}><div className={`equipment-icon ${item.status.toLowerCase()}`}><Radio size={24}/><i/><i/><i/></div><small>{item.id}</small><span>{item.status}</span></div>)}</div></VisualCard>;
  right=<VisualCard kicker="ASSET AVAILABILITY" title="Warehouse to customer" caption="Current equipment status across your inventory."><Donut data={sums(items,'status')} label="devices"/></VisualCard>;
 }else if(page==='Billing & payments'){
  left=<VisualCard kicker="COLLECTION MIX" title="Cash collected. Balance visible." caption="Invoice totals, grouped by payment status."><Donut data={['Paid','Due','Overdue'].map((name,i)=>({name,value:bills.filter(b=>b.status===name).reduce((s,b)=>s+b.amount,0),color:[colors[0],colors[2],colors[1]][i]}))} label="invoiced" format={money}/></VisualCard>;
  right=<VisualCard kicker="COLLECTION CHANNELS" title="How payments reach you" caption="Paid invoices only · Values are in BDT."><BarRows data={sums(bills.filter(b=>b.status==='Paid'),'method','amount')} format={money}/></VisualCard>;
 }else if(page==='Network'||page==='Service areas'){
  left=<VisualCard kicker="UPLINK PRESSURE / DEMO" title="Spot the bottleneck before the call" caption="80% is the planning threshold. Dhanmondi needs attention."><div className="pop-dot-bars">{[{name:'Gulshan',value:62},{name:'Banani',value:41},{name:'Dhanmondi',value:88},{name:'Uttara',value:53}].map(d=><div key={d.name}><span>{d.name}</span><DotMeter value={d.value} color={d.value>80?'orange':'cyan'} count={24}/><b>{d.value}%</b></div>)}</div></VisualCard>;
  right=<VisualCard kicker="LATENCY / DEMO" title="One view. Every point of presence." caption="Round-trip latency in milliseconds · Target below 10 ms."><BarRows data={[{name:'Gulshan',value:3.2},{name:'Banani',value:2.8},{name:'Dhanmondi',value:12.4,color:colors[1]},{name:'Uttara',value:3.4}]} max={20} suffix=" ms"/></VisualCard>;
 }else if(page==='Reports'){
  left=<VisualCard kicker="REVENUE COMPOSITION" title="What drives recurring revenue" caption="Current customer plan prices, before any credits or tax."><Donut data={sums(customers,'plan','price')} label="monthly BDT" format={money}/></VisualCard>;
  right=<VisualCard kicker="SERVICE OUTCOMES" title="Work completed, made visible" caption="Based on current support and field-service records."><div className="outcome-meters">{[{name:'Tickets resolved',a:tickets.filter(t=>t.status==='Resolved').length,b:tickets.length},{name:'Visits completed',a:jobs.filter(j=>j.status==='Completed').length,b:jobs.length},{name:'Invoices paid',a:bills.filter(b=>b.status==='Paid').length,b:bills.length}].map(d=><div key={d.name}><span>{d.name}<b>{d.a}/{d.b}</b></span><DotMeter value={d.a/Math.max(d.b,1)*100} count={30}/></div>)}</div></VisualCard>;
 }else if(page==='Notifications'){
  left=<VisualCard kicker="EVENT ROUTING" title="Every signal has a destination" caption="Illustrative event categories represented in this demo feed."><div className="event-routes"><div><Radio size={20}/><small>Network</small></div><div><Wallet size={20}/><small>Billing</small></div><div><Headphones size={20}/><small>Support</small></div><ArrowRight size={21}/><div className="event-destination"><Bell size={24}/><small>In-app feed</small></div></div></VisualCard>;
  right=<VisualCard kicker="INBOX STATE" title={read?'All caught up':'Four updates, one place'} caption="Read status reflects this notification center."><div className="notification-dots">{Array.from({length:4},(_,i)=><span key={i} className={read?'read':''}>{read?<Check size={24}/>:<Bell size={22}/>}</span>)}</div><p className="visual-explanation">{read?'All 4 seeded notifications are marked as read.':'4 seeded updates are waiting for review.'}</p></VisualCard>;
 }else if(page==='Settings'){
  left=<VisualCard kicker="NOTIFICATION PREFERENCES" title="Your operational signal paths" caption="Local preferences only; no external gateway is connected."><div className="settings-signals">{[['Network incidents',settings.alerts],['Payment reminders',settings.reminders]].map(([name,on])=><div key={name}><Radio size={17}/><span>{name}</span><div className={on?'signal-path enabled':'signal-path'}/><Bell size={17}/><b>{on?'On':'Off'}</b></div>)}</div></VisualCard>;
  right=<VisualCard kicker="WORKSPACE BOUNDARY" title="A safe space to explore" caption="This is a frontend demonstration with local browser storage."><div className="workspace-visual"><ShieldCheck size={42}/><div><strong>Local demo</strong><p>Seeded records <span>→</span> Your browser</p><span>No live network or payment access</span></div></div></VisualCard>;
 }else if(page==='Customer portal'){
  left=<VisualCard kicker="YOUR CONNECTION / DEMO" title="A week of staying connected" caption="Illustrative daily usage in GB. This is not metered account data."><div className="usage-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={[{day:'M',gb:12},{day:'T',gb:8},{day:'W',gb:17},{day:'T',gb:11},{day:'F',gb:22},{day:'S',gb:29},{day:'S',gb:18}]}><CartesianGrid stroke="#354248" vertical={false}/><XAxis dataKey="day" tick={{fontSize:10,fill:'#94a5ac'}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#263035',border:'1px solid #54646c'}}/><Area dataKey="gb" stroke="#91b9c0" fill="#91b9c0" fillOpacity={.13}/></AreaChart></ResponsiveContainer></div></VisualCard>;
  right=<VisualCard kicker="SERVICE STATUS" title="Your connection, explained" caption="Package and status come from your customer record."><div className="portal-speed"><Signal size={31}/><b>{customers[0].speed}<small>Mbps</small></b><span>{customers[0].plan}</span></div><DotMeter value={customers[0].status==='Active'?100:0} count={36}/><p className="visual-explanation">{customers[0].status} · Unlimited data</p></VisualCard>;
 }else return null;
 return <div className="page-insights">{left}{right}</div>;
}
